image: python:3-stretch

#build:
#  stage: build
#  script:
#    - ./.gitlab/ci/build.sh
#  artifacts:
#    paths:
#      - njvm

test:
  stage: test
  tags:
    - python3
  script:
    - ./.gitlab/ci/test.sh
